// <auto-generated />
using System;
using CreApps.StarterKit.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreApps.StarterKit.DataAccess.Migrations
{
    [DbContext(typeof(StarterKitDbContext))]
    [Migration("20190417163432_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CreApps.StarterKit.Models.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("PriorityName");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("Priority");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(3275),
                            PriorityName = "Critical",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(3280)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(4339),
                            PriorityName = "Urgent",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(4344)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(4351),
                            PriorityName = "Medium",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(4352)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(4353),
                            PriorityName = "Low",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(4354)
                        });
                });

            modelBuilder.Entity("CreApps.StarterKit.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("StatusName");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(5718),
                            StatusName = "Pending",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(5721)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(6593),
                            StatusName = "In progress",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(6595)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(6601),
                            StatusName = "Resolved",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(6602)
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(6603),
                            StatusName = "Closed",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(6604)
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(6605),
                            StatusName = "Discarted",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 36, DateTimeKind.Local).AddTicks(6606)
                        });
                });

            modelBuilder.Entity("CreApps.StarterKit.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<int>("PriorityId");

                    b.Property<int>("StatusId");

                    b.Property<string>("Subject");

                    b.Property<int>("TypeId");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("CreApps.StarterKit.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("TicketTypeName");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("TicketType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 32, DateTimeKind.Local).AddTicks(1224),
                            TicketTypeName = "Problem",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 33, DateTimeKind.Local).AddTicks(4062)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 33, DateTimeKind.Local).AddTicks(7043),
                            TicketTypeName = "Incident",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 33, DateTimeKind.Local).AddTicks(7051)
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 33, DateTimeKind.Local).AddTicks(7060),
                            TicketTypeName = "New Requirement",
                            UpdatedOn = new DateTime(2019, 4, 17, 11, 34, 32, 33, DateTimeKind.Local).AddTicks(7061)
                        });
                });

            modelBuilder.Entity("CreApps.StarterKit.Models.Ticket", b =>
                {
                    b.HasOne("CreApps.StarterKit.Models.Priority", "Priority")
                        .WithMany("Tickets")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CreApps.StarterKit.Models.Status", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CreApps.StarterKit.Models.TicketType", "Type")
                        .WithMany("Tickets")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
